version: '3'
services:
  nginx:
    image: nginx:1.18.0
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0.19
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html

  supervisor:
    build:
      context: ./docker/supervisor
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html

volumes:
  db_vol: